### ISSUE TITLE
Feature Request: parsing .github/CODEOWNERS for reviewers

### ISSUE THREAD

**Issue by SivanMehta** [godaddy/pullie#31]
Currently, relying on a `package.json` falls short in specifying maintainers / reviewers for 2 reasons.

1. Repos that aren't `.js` focused are unlikely to have a `package.json`.
2. Monorepos that encapsulate many other repos may have divergent skillsets needed for accurate PR reviews.

Turns out that Github **already** has a tool for this: [`.github/CODEOWNERS` file](https://github.blog/2017-07-06-introducing-code-owners/). Pullie should support using that file, if present, in addition to `package.json`

**Comment by decompil3d** [comment]
If you make a CODEOWNERS file, GitHub is going to manage requesting reviews itself, so there would be no need for using Pullie's reviewers plugin at all.
